import { createHash } from "node:crypto";
import { existsSync, readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import type { Database as SqliteConnection } from "better-sqlite3";
import { t } from "../i18n/index.js";
import { MigrationError, StorageError } from "./errors.js";

/**
 * Applying the migrations that drizzle-kit generated (ADR-002).
 *
 * drizzle-kit writes the SQL and the journal; this module is the runner the
 * application calls at start, and it exists instead of `drizzle-orm`'s own
 * `migrate()` for one reason: that helper drops the migration tag when it reads
 * the folder, so a failure surfaces as a bare SQLite error with no way to say
 * WHICH migration broke, and the ledger it writes records only a hash. The
 * acceptance criteria of this phase require the opposite on all three counts:
 *
 *   - 19: pending migrations are applied and what was applied is recorded;
 *   - 20: a failing migration stops the process, naming the migration;
 *   - 21: an already migrated database reapplies nothing.
 *
 * Each migration runs inside a transaction together with its ledger row, so a
 * statement that fails half way leaves neither a partial schema nor a row
 * claiming success.
 */

/** Where the ledger of applied migrations lives. */
export const MIGRATIONS_TABLE = "__mychat_migrations";

/** Separator drizzle-kit writes between statements of one migration. */
const STATEMENT_BREAKPOINT = "--> statement-breakpoint";

/**
 * Default folder, resolved from this module rather than from the working
 * directory: the process must find its migrations however it was launched.
 */
export const DEFAULT_MIGRATIONS_FOLDER = fileURLToPath(
  new URL("../../drizzle", import.meta.url),
);

/** One migration as generated by drizzle-kit, ready to be applied. */
export interface Migration {
  /** File name without extension, such as `0000_initial`. */
  readonly tag: string;
  readonly statements: readonly string[];
  /** Hash of the file content, so an edited migration is caught, not replayed. */
  readonly checksum: string;
}

/** What a start-up run of the migrations did, for the caller to log. */
export interface MigrationReport {
  /** Tags applied by this run, in order. */
  readonly applied: readonly string[];
  /** Tags already present in the ledger, left untouched. */
  readonly alreadyApplied: readonly string[];
}

interface JournalEntry {
  readonly tag: string;
}

/**
 * Reads the migrations drizzle-kit generated, in the order of its journal.
 * Order comes from the journal and never from directory listing, because
 * lexical order and intended order are not the same guarantee.
 */
export function readMigrations(
  folder: string = DEFAULT_MIGRATIONS_FOLDER,
): readonly Migration[] {
  const journalPath = `${folder}/meta/_journal.json`;

  if (!existsSync(journalPath)) {
    throw new StorageError(t("storage.journalMissing", { path: journalPath }));
  }

  const journal = JSON.parse(readFileSync(journalPath, "utf8")) as {
    entries?: readonly JournalEntry[];
  };

  return (journal.entries ?? []).map((entry) => {
    const path = `${folder}/${entry.tag}.sql`;

    if (!existsSync(path)) {
      throw new StorageError(
        t("storage.migrationFileMissing", { tag: entry.tag, path }),
      );
    }

    const content = readFileSync(path, "utf8");

    return {
      tag: entry.tag,
      statements: content
        .split(STATEMENT_BREAKPOINT)
        .map((statement) => statement.trim())
        .filter((statement) => statement !== ""),
      checksum: createHash("sha256").update(content).digest("hex"),
    };
  });
}

/**
 * Applies every pending migration and returns what it did. Called once at
 * start-up by `openDatabase`, before anything is allowed to serve.
 */
export function runMigrations(
  connection: SqliteConnection,
  migrations: readonly Migration[] = readMigrations(),
): MigrationReport {
  createLedger(connection);

  const ledger = readLedger(connection);
  const applied: string[] = [];
  const alreadyApplied: string[] = [];

  for (const migration of migrations) {
    const recorded = ledger.get(migration.tag);

    if (recorded !== undefined) {
      if (recorded !== migration.checksum) {
        throw new MigrationError(
          migration.tag,
          t("storage.migrationChecksumMismatch", { tag: migration.tag }),
        );
      }
      alreadyApplied.push(migration.tag);
      continue;
    }

    apply(connection, migration);
    applied.push(migration.tag);
  }

  return { applied, alreadyApplied };
}

/** The tags recorded as applied, for a caller that only wants the ledger. */
export function readAppliedMigrations(
  connection: SqliteConnection,
): readonly string[] {
  createLedger(connection);
  return [...readLedger(connection).keys()];
}

function createLedger(connection: SqliteConnection): void {
  connection.exec(
    `CREATE TABLE IF NOT EXISTS ${MIGRATIONS_TABLE} (
       tag TEXT PRIMARY KEY,
       checksum TEXT NOT NULL,
       applied_at INTEGER NOT NULL
     )`,
  );
}

function readLedger(connection: SqliteConnection): Map<string, string> {
  const rows = connection
    .prepare(`SELECT tag, checksum FROM ${MIGRATIONS_TABLE} ORDER BY tag`)
    .all() as { tag: string; checksum: string }[];

  return new Map(rows.map((row) => [row.tag, row.checksum]));
}

function apply(connection: SqliteConnection, migration: Migration): void {
  const record = connection.prepare(
    `INSERT INTO ${MIGRATIONS_TABLE} (tag, checksum, applied_at) VALUES (?, ?, ?)`,
  );

  // Schema change and ledger row commit together, or neither does.
  const transaction = connection.transaction(() => {
    for (const statement of migration.statements) {
      connection.exec(statement);
    }
    record.run(migration.tag, migration.checksum, Date.now());
  });

  try {
    transaction();
  } catch (cause) {
    throw new MigrationError(
      migration.tag,
      t("storage.migrationFailed", {
        tag: migration.tag,
        reason: describe(cause),
      }),
      { cause },
    );
  }
}

function describe(cause: unknown): string {
  return cause instanceof Error ? cause.message : String(cause);
}
